#include<iostream.h>
void main()
{
	outtextxy("PROGRAMMED BY");
	outtextxy("Saiyam Goel");
	outtextxy("Sahil Singh");
	outtextxy("Mayank Dawra");
	outtextxy("Mohd. Mossdiq Hasan");
	outtextxy("DEVELOPED BY");
	outtextxy("Saiyam Goel");
	outtextxy("Sahil Singh");
	outtextxy("DESIGNED BY");
	outtextxy("Sahil Singh");
	outtextxy("Mayank Dawra");
	outtextxy("Saiyam Goel");
	outtextxy("INTEGRATED & TESTED BY");
	outtextxy("Mayank Dawra");
	outtextxy("Mohd. Mossdiq Hasan");
	outtextxy("DOCUMENTED BY");
	outtextxy("Mohd. Mossdiq Hasan");
	outtextxy("COPYRIGHT NOT HOT PRODUCTIONS, INC. 2015");
}